name: Periodic health check

# TODO: Change trigger
on:
  push:
    branches:
      - master

jobs:
  periodic_health_check:
    runs-on: ubuntu-18.04
    steps:
    - name: Check the deployed service URL
      uses: jtalk/url-health-check-action@v1.5
      with:
        url: https://podedex-jp-2021.herokuapp.com/
        follow-redirect: no
        max-attempts: 3
        retry-delay: 5s
        retry-all: no